std = "roblox"

[rules]
almost_swapped = "deny"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "allow"
global_usage = "allow"
if_same_then_else = "deny"
ifs_same_cond = "deny"
multiple_statements = "warn"
one_line_if = "allow"
mismatched_arg_count = "warn"
parenthese_conditions = "warn"
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "deny"
shadowing = "allow"
incorrect_standard_library_use = "allow"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "warn"
undefined_variable = "deny"
unscoped_variables = "warn"
unused_variable = "warn"